version: '3'
services:
  springboot-hystrix:
    image: springboot-hystrix:1.0
    ports:
    - "8081:8080"
    volumes:
      - $PWD/logs/:/tmp/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "3"
    container_name: "springboot-hystrix"
