logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.circuitbreaker: DEBUG
  file: logs/HystrixCB.log
  pattern:
    console:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# The format used for the keystore. It could be set to JKS in case it is a JKS file
# The path to the keystore containing the certificate
# The password used to generate the certificate
# The alias mapped to the certificate
#server.ssl:
#  key-store-type: JKS
#  key-store: classpath:keystore/ssl-cert.jks
#  key-store-password: changeit
#  key-password: changeit
#  enabled: true

#https.port: ${https_port}
#http.port: ${http_port}